POST http://localhost:8081/sign-in
Content-Type: application/json
Cookie: token=16166777948950458

{
  "firstName": "Billy",
  "lastName": "Bones",
  "email": "billy.bones@ria.com",
  "pass": "123456789",
  "isAdmin": 1
}